apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: default-pool
  namespace: metallb-system
spec:
  addresses:
    - 192.168.1.10-192.168.1.250
---
apiVersion: metallb.io/v1beta2
kind: BGPPeer
metadata:
  name: udm
  namespace: metallb-system
spec:
  myASN: 65002        # MetalLB speakers (cluster ASN)
  peerASN: 65001      # UDM Pro ASN
  peerAddress: 192.168.0.1
---
apiVersion: metallb.io/v1beta1
kind: BGPAdvertisement
metadata:
  name: default-adv
  namespace: metallb-system
spec:
  ipAddressPools:
    - default-pool